### ISSUE TITLE
Please, consider updating CFLAGS in makefile for MacOS

### ISSUE THREAD

**Issue by isnikulin** [Swoorup/mysh#2]
Hi, the make command fails to build on MacOS Mojave. Here is the log:

> 
> gcc -m32 -c lexer.c
> gcc -m32 -c shell.c
> gcc -m32 -c parser.c
> gcc -m32 -c astree.c
> gcc -m32 -c execute.c
> gcc -m32 -c command.c
> command.c:226:9: warning: implicit declaration of function 'sigfillset' is invalid in C99 [-Wimplicit-function-declaration]
>         sigfillset( & (act.sa_mask) ); // to block all
>         ^
> command.c:228:13: warning: implicit declaration of function 'sigaction' is invalid in C99 [-Wimplicit-function-declaration]
>         if (sigaction(SIGCHLD, &act, NULL) != 0)
>             ^
> 2 warnings generated.
> gcc -m32 parser.o lexer.o shell.o astree.o execute.o command.o -o shell
> ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
> ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd
> Undefined symbols for architecture i386:
>   "___assert_rtn", referenced from:
>       _ASTreeAttachBinaryBranch in astree.o
>       _ASTreeNodeSetType in astree.o
>       _ASTreeNodeSetData in astree.o
>   "___error", referenced from:
>       _main in shell.o
>   "___stack_chk_fail", referenced from:
>       _execute_pipeline in execute.o
>       _execute_pwd in command.o
>   "___stack_chk_guard", referenced from:
>       _execute_pipeline in execute.o
>       _execute_pwd in command.o
>       _execute_pipeline in execute.o
>       _execute_pwd in command.o
>   "___stdinp", referenced from:
>       _main in shell.o
>   "___stdoutp", referenced from:
>       _execute_pwd in command.o
>   "___strcpy_chk", referenced from:
>       _term in parser.o
>       _strip_quotes in lexer.o
>       _lexer_build in lexer.o
>       _set_prompt in command.o
>       _init_command_internal in command.o
>   "_chdir", referenced from:
>       _execute_cd in command.o
>   "_clearerr", referenced from:
>       _main in shell.o
>   "_close$UNIX2003", referenced from:
>       _execute_pipeline in execute.o
>   "_dup", referenced from:
>       _execute_command_internal in command.o
>   "_dup2", referenced from:
>       _execute_pwd in command.o
>       _execute_command_internal in command.o
>   "_execvp", referenced from:
>       _execute_command_internal in command.o
>   "_exit", referenced from:
>       _main in shell.o
>       _execute_pwd in command.o
>       _execute_command_internal in command.o
>   "_feof", referenced from:
>       _main in shell.o
>   "_fork", referenced from:
>       _execute_pwd in command.o
>       _execute_command_internal in command.o
>   "_fprintf", referenced from:
>       _execute_pwd in command.o
>   "_free", referenced from:
>       _CMD1 in parser.o
>       _CMD2 in parser.o
>       _tok_destroy in lexer.o
>       _lexer_build in lexer.o
>       _main in shell.o
>       _ASTreeNodeDelete in astree.o
>       _set_prompt in command.o
>       ...
>   "_getcwd", referenced from:
>       _execute_pwd in command.o
>   "_getline", referenced from:
>       _main in shell.o
>   "_getpwuid", referenced from:
>       _execute_cd in command.o
>   "_getuid", referenced from:
>       _execute_cd in command.o
>   "_glob$INODE64", referenced from:
>       _lexer_build in lexer.o
>   "_malloc", referenced from:
>       _term in parser.o
>       _CMDLINE1 in parser.o
>       _CMDLINE2 in parser.o
>       _CMDLINE3 in parser.o
>       _CMDLINE4 in parser.o
>       _JOB1 in parser.o
>       _CMD1 in parser.o
>       ...
>   "_open$UNIX2003", referenced from:
>       _execute_pwd in command.o
>       _execute_command_internal in command.o
>   "_perror", referenced from:
>       _execute_cd in command.o
>       _execute_pwd in command.o
>       _execute_command_internal in command.o
>   "_pipe", referenced from:
>       _execute_pipeline in execute.o
>      (maybe you meant: _execute_pipeline)
>   "_printf", referenced from:
>       _parse in parser.o
>       _main in shell.o
>       _execute_cd in command.o
>       _execute_prompt in command.o
>       _zombie_process_handler in command.o
>       _execute_command_internal in command.o
>   "_sigaction", referenced from:
>       _execute_command_internal in command.o
>   "_sigfillset", referenced from:
>       _execute_command_internal in command.o
>   "_signal", referenced from:
>       _ignore_signal_for_shell in command.o
>       _restore_sigint_in_child in command.o
>      (maybe you meant: _ignore_signal_for_shell, _signalset )
>   "_strcmp", referenced from:
>       _execute_command_internal in command.o
>   "_strlen", referenced from:
>       _term in parser.o
>       _strip_quotes in lexer.o
>       _lexer_build in lexer.o
>       _set_prompt in command.o
>       _init_command_internal in command.o
>   "_waitpid$UNIX2003", referenced from:
>       _execute_pwd in command.o
>       _zombie_process_handler in command.o
>       _execute_command_internal in command.o
> ld: symbol(s) not found for architecture i386
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [shell] Error 1

However, the whole issue goes away if you change 
`CFLAGS = -m32`
to
`CFLAGS = -m64`

I am not aware how this change might affect other platforms, however.

**Comment by Swoorup** [comment]
That is a reasonable change. @Preposterone 
Do you want to submit a pull request? I don't think we should be worried about 32 bit?

**Comment by isnikulin** [comment]
Sure, done, thanks.
